### ISSUE TITLE
Start tracking telemetry with LearnPack

### ISSUE THREAD

**Issue by tommygonzaleza** [learnpack/learnpack#1211]
### 4Geeks Backend Tasks:

- [ ] Create an endpoint that generates a telemetry token (it should be limited to the user's `id` and basic information). 
- [ ] We should also include the columns of the data we would like to collect from LearnPack in the Assessment's model (Still thinking about the best approach? Maybe it could be better to have a table where I register all the user's activity in LearnPack and generate a report from it). 
- [ ] Create a URL where the telemetry data will be received.

### 4Geeks Frontend Tasks:

- [ ] Generate a telemetry token with the endpoint given by the backend.
- [ ] In the query string of the URL that takes the user to the exercise in gitpod, we should include the URL of the endpoint and the telemetry token.

### LearnPack:

- [ ] Store the URL and token given through gitpod's URL query string as environment variables.
- [ ] Use the environment variables for the URL and token in LearnPack's CLI to push all the activity's information (Exercises completed, times the user tested an exercise until completed, compiler errors, time spent on completing an exercise, bugs reported by the user, etc)
